# Popover Details Configuration
# This file contains the lookup table and helper function for rendering 
# "Details" buttons with custom popovers next to download buttons.
#
# Structure:
#   - `details_lookup`: tibble mapping section_id to title and description text
#   - `create_details_button()`: helper function to render Details button with popover

# ============================================================================
# Details Lookup Table
# ============================================================================
# Instructions for adding entries:
# - section_id: matches the output$* ID from main_page_server.R
# - details_title: short, clear title for the popover
# - details_text: 1-3 sentence description of what the visualization shows
#

details_lookup <- tribble(
  ~section_id,              ~details_title,                        ~details_text,
  # ========== Demographics Section ==========
  "sex1",                  "Sex Details",                     "This plot shows the percent of people with HIV served at your clinic, by sex regardless of LAI ART use.",
  "race1",                 "Race Details",                    "This plot shows the percent of people with HIV served at your clinic, by race regardless of LAI ART use.",
  "ethnicity1",            "Ethnicity Details",               "This plot shows the percent of people with HIV served at your clinic, by ethnicity regardless of LAI ART use.",
  "age1",                  "Age Details",                     "This plot shows the percent of people with HIV served at your clinic, by age regardless of LAI ART use.",
  "insurance1",            "HIV Medication Payor Details",    "This plot shows the percent of people with HIV served at your clinic, by HIV medication payor regardless of LAI ART use. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). ",
  "keypop1",               "Key Population Details",          "This plot shows the percent of people with HIV served at your clinic, by key population regardless of LAI ART use. Key populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. ",
  "zip_map_1",             "Zip Code Map Details",            "This map shoes where people with HIV served at your clinic live. Darker colors indicate a higher concentration of clients, while lighter colors indicate a lower concentration of clients. ",
  
  # ========== Demographics by LAI ART Section ==========
  "sex1b",                 "Sex Details",                     "This plot shows the distribution of sex within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the sex variable, users can compare the dark blue bars (ever on LAI ART) for a variable category (e.g., female) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic.  ",
  "race1b",                "Race Details",                    "This plot shows the distribution of race within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the race variable, users can compare the dark blue bars (ever on LAI ART) for a variable category (e.g., Black) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic. ",
  "ethnicity1b",           "Ethnicity Details",               "This plot shows the distribution of ethnicity within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the ethnicity variable, users can compare the dark blue bars (ever on LAI ART) for a variable category (e.g., Hispanic) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic. ",
  "age1b",                 "Age Details",                     "This plot shows the distribution of age within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the age variable, users can compare the dark blue bars (ever on LAI ART) for a variable category (e.g., age 18-24) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic.  ",
  "insurance1b",           "HIV Medication Payor Details",    "This plot shows the distribution of HIV medication payor within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the HIV medication payor variable, users can compare the dark blue bars (ever on LAI ART) for a variable category (e.g., Uninsured) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic.  ",
  "keypop1b",              "Key Population Details",          "This plot shows the distribution of key population within a population of clients ever on LAI ART and a population of clients never on LAI ART. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who were ever on LAI ART differ from clients who were never on LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the dark blue bars (ever on LAI ART) for a variable category (e.g., unstable housing) to the light blue bars (never on LAI ART) for the same variable category. Differences in these values represent a care gap where one variable category are over or under represented among clients ever on LAI ART, relative to their representativeness at the clinic.  ",
  "zip_map_1b",            "Zip Code Map Details",            "This map shoes where people with HIV served at your clinic who have ever been on LAI ART live. Darker colors indicate a higher concentration of clients, while lighter colors indicate a lower concentration of clients. ",
  
  # ========== LAI Care Gap Analysis ==========
  "lai_care_gap",          "Care Gap Analysis Details",             "This plot shows the proportion of clients at a clinic who have been Assessed for LAI ART, are Interested and Eligible for LAI ART, have been Prescribed LAI ART, Initiated LAI ART, and are Sustained on LAI ART. This gives an overview of where the “gaps” in getting clients on LAI ART are occurring. Note that Assessed and Interested and Eligible can be hidden if counseling and screening are not consistently recorded, per the Dashboard preferences in the Navigation Panel.",
  "assessed_outcomes",     "Assessed Outcomes Details",             "The \"Outcomes among those assessed\" table shows the distribution of counseling and screening outcomes among those assessed. The \"Percent\" buttons allow you to change how the percentages are calculated: \"Table\" for using the number assessed as the denominator, \"Row\" for using the row total, and \"Column\" for using the column total. For example, to see the percentage eligible among those interested, using the row percent is best. The highlighted cell shows the number of people who are interested and eligible, as in the LAI ART care gap analysis.",
  
  # ========== Assessed Section ==========
  "assessed_overall",      "Assessed Overall",                     "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART.",
  "sex2",                  "Assessed by Sex",                      "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by sex. \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the sex variable, users can compare the bars (ever assessed for LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of sex).",
  "race2",                 "Assessed by Race",                     "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by race. \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the race variable, users can compare the bars (ever assessed for LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of race).",
  "ethnicity2",            "Assessed by Ethnicity",                "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by ethnicity. \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the ethnicity variable, users can compare the bars (ever assessed for LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of ethnicity).",
  "age2",                  "Assessed by Age",                      "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by age. \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the age variable, users can compare the bars (ever assessed for LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of age).",
  "insurance2",            "Assessed by HIV Medication Payor",     "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the HIV medicator payor variable, users can compare the bars (ever assessed for LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of HIV medication payor).",
  "keypop2",               "Assessed by Key Population",           "This plot shows the percent of people with HIV served at your clinic who have been assessed for LAI ART, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who were ever assessed for LAI ART differ from clients who were never assessed for LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (ever assessed for LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients ever assessed for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of key population).",
  "time2",                 "Assessed Over Time (by person)",       "Assessed over time by person shows the number of people assessed by month, based on their most recent assessment date. \n\u2022 Each person can show up at most 1 time\n\u2022 The date reflects their most recent assessment. If a person was assessed multiple times, only the most recent assessment is reflected.",
  "time2_event",           "Assessed Over Time (by encounter)",    "Assessed over time by encounter shows the number of assessments occurring each month. This includes all unique dates when a person was assessed. \n\u2022 Each person can show up multiple times \n\u2022 The date reflects the date the assessment occurred \n\nIf counseling and screening were on the same date, they will count as 1 encounter. If they were on different dates, they will count as multiple encounters.",
  
  # ========== Counseled Section ==========
  "counseled_overall",     "Counseled Overall",                    "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART.",
  "sex3",                  "Counseled by Sex",                     "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by sex. \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the sex variable, users can compare the bars (ever counseled for LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever assessed for LAI ART regardless of sex).",
  "race3",                 "Counseled by Race",                    "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by race. \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the race variable, users can compare the bars (ever counseled for LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever counseled for LAI ART regardless of race).",
  "ethnicity3",            "Counseled by Ethnicity",               "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by ethnicity. \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the ethnicity variable, users can compare the bars (ever counseled for LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever counseled for LAI ART regardless of ethnicity).",
  "age3",                  "Counseled by Age",                     "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by age. \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the age variable, users can compare the bars (ever counseled for LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever counseled for LAI ART regardless of age).",
  "insurance3",            "Counseled by HIV Medication Payor",    "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the HIV medicator payor variable, users can compare the bars (ever counseled for LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever counseled for LAI ART regardless of HIV medication payor).",
  "keypop3",               "Counseled by Key Population",          "This plot shows the percent of people with HIV served at your clinic who have been counseled for LAI ART, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who were ever counseled for LAI ART differ from clients who were never counseled for LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (ever counseled for LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever counseled for LAI ART regardless of key population).",
  "time3",                 "Counseled Over Time (by person)",      "Counseled over time by person shows the number of people counseled by month, based on their most recent counseling date.\n\u2022 Each person can show up at most 1 time \n\u2022 The date reflects their most recent counseling event. If a person was counseled multiple times, only the most recent counseling event is reflected.",
  "time3_event",           "Counseled Over Time (by encounter)",   "Counseled over time by encounter shows the number of counseling events occurring each month. This includes all unique dates when a person was counseled. \n\u2022 Each person can show up multiple times \n\u2022 The date reflects the date the counseling encounter  occurred",
  
  # ========== Interested Section ==========
  "interested_overall",    "Interested Overall",                       "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled.",
  "sex4",                  "Interested by Sex",                        "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by sex. \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the sex variable, users can compare the bars (interested in LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients interested in LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of sex).",
  "race4",                 "Interested by Race",                       "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by race. \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the race variable, users can compare the bars (interested in LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients interested in LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of race).",
  "ethnicity4",            "Interested by Ethnicity",                  "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by ethnicity. \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the ethnicity variable, users can compare the bars (interested in LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients interested in LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of ethnicity).",
  "age4",                  "Interested by Age",                        "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by age. \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the age variable, users can compare the bars (interested in LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients interested in LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of age).",
  "insurance4",            "Interested by HIV Medication Payor",       "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the HIV medicator payor variable, users can compare the bars (interested in LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients interested in LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of HIV medication payor).",
  "keypop4",               "Interested by Key Population",             "This plot shows the percent of people with HIV served at your clinic who are interested in LAI ART after being counseled, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who are interested in LAI ART differ from clients who are not interested in LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (interested in LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients ever counseled for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients interested in LAI ART regardless of key population).",
  "time4",                 "Interested Over Time (by person)",         "Interested over time by person shows the number of people interested by month, based on their most recent counseling date, with the color representing the number interested/maybe interested/not interested. \n\u2022 Each person can show up at most 1 time \n\u2022 The date reflects their most recent counseling event. If a person was counseled multiple times, only the most recent counseling event is reflected.",
  "time4_event",           "Interested Over Time (by encounter)",      "Interested over time by encounter shows the number of counseling events occurring each month. This includes all unique dates when a person was counseled. The color represents the number interested/maybe interested/not interested. \n\u2022 Each person can show up multiple times \n\u2022 The date reflects the date the counseling occurred",
  "not_interested_reason", "Reasons Not Interested",                   "The not interested reasons plot displays the number and percent reporting each reason among those maybe interested or not interested at their most recent counseling encounter. \n\nNote that interpretation of this chart will depend on how the variable \"disinterest_reason\" was coded. A clinic could choose to collect the primary reason for disinterest or multiple reasons for disinterest. If a clinic collected data on multiple reasons for disinterest, the interpretation of the plot is as follows: \n\u2022 If the primary reason is reported in the \"reason\" column, and other reasons are reported in the \"other\" column, then the denominator of the bar chart is the number of clients not interested in iCAB/RPV. \n\u2022 If all disinterest reasons are reported, separated by commas, then the denominator of the bar chart is the total number of reasons provided for iCAB/RPV disinterest among clients counseled about iCAB/RPV.",
  
  # ========== Screened Section ==========
  "screened_overall",      "Screened Overall",                         "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility.",
  "sex5",                  "Screened by Sex",                          "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by sex. \n\nTo compare whether clients who were ever screened for LAI ART  differ from clients who were never screened for LAI ART for the sex variable, users can compare the bars (ever screened for LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of sex).",
  "race5",                 "Screened by Race",                         "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by race. \n\nTo compare whether clients who were ever screened for LAI ART differ from clients who were never screened for LAI ART for the race variable, users can compare the bars (ever screened for LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of race).",
  "ethnicity5",            "Screened by Ethnicity",                    "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by ethnicity. \n\nTo compare whether clients who were ever screened for LAI ART differ from clients who were never screened for LAI ART for the ethnicity variable, users can compare the bars (ever screened for LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of ethnicity).",
  "age5",                  "Screened by Age",                          "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by age. \n\nTo compare whether clients who were ever screened for LAI ART differ from clients who were never screened for LAI ART for the age variable, users can compare the bars (ever screened for LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of age).",
  "insurance5",            "Screened by HIV Medication Payor",         "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who were ever screened for LAI ART differ from clients who were never screened for LAI ART for the HIV medicator payor variable, users can compare the bars (ever screened for LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of HIV medication payor).",
  "keypop5",               "Screened by Key Population",               "This plot shows the percent of people with HIV served at your clinic who have been screened for LAI ART eligibility, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who were ever screened for LAI ART differ from clients who were never screened for LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (ever screened for LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients ever screened for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever screened for LAI ART regardless of key population).",
  "time5",                 "Screened Over Time (by person)",           "Screened over time by person shows the number of people screened by month, based on their most recent screening date. \n\u2022 Each person can show up at most 1 time \n\u2022 The date reflects their most recent screening event. If a person was screened multiple times, only the most recent screening event is reflected.",
  "time5_event",           "Screened Over Time (by encounter)",        "Screened over time by encounter shows the number of screening events occurring each month. This includes all unique dates when a person was screened. \n\u2022 Each person can show up multiple times \n\u2022 The date reflects the date the screening occurred",
  
  # ========== Eligible Section ==========
  "eligible_overall",      "Eligible Overall",                         "This plot shows the percent of people with HIV served at your clinic who are  eligible for LAI ART after being screened.",
  "sex6",                  "Eligible by Sex",                          "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by sex. \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the sex variable, users can compare the bars (eligible for LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of sex).",
  "race6",                 "Eligible by Race",                         "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by race. \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the race variable, users can compare the bars (eligible for LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of race).",
  "ethnicity6",            "Eligible by Ethnicity",                    "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by ethnicity. \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the ethnicity variable, users can compare the bars (eligible for LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of ethnicity).",
  "age6",                  "Eligible by Age",                          "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by age. \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the age variable, users can compare the bars (eligible for LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of age).",
  "insurance6",            "Eligible by HIV Medication Payor",         "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the HIV medicator payor variable, users can compare the bars (eligible for LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of HIV medication payor).",
  "keypop6",               "Eligible by Key Population",               "This plot shows the percent of people with HIV served at your clinic who are eligible for LAI ART after being screened, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who are eligible for LAI ART differ from clients who are not eligible for LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (eligible for LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients eligible for LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients eligible for LAI ART regardless of key population).",
  "time6",                 "Eligible Over Time (by person)",           "Eligible over time by person shows the number of people eligible by month, based on their most recent screening date, with the color representing the number eligible/not eligible. \n\u2022 Each person can show up at most 1 time \n\u2022 The date reflects their most recent screening event. If a person was screened multiple times, only the most recent screening event is reflected.",
  "time6_event",           "Eligible Over Time (by encounter)",        "Eligible over time by encounter shows the number of screening events occurring each month. This includes all unique dates when a person was screened. The color represents the number eligible/not eligible. \n\u2022 Each person can show up multiple times \n\u2022 The date reflects the date the screening occurred",
  "not_eligible_reason",   "Reasons Not Eligible",                     "The not eligible reasons plot displays the number and percent reporting each reason among those not eligible at their most recent screening encounter. \n\nNote that interpretation of this chart will depend on how the variable \"not_eligible_reason\" was coded. A clinic could choose to collect the primary reason for non-eligibility or multiple reasons for non-eligibility. If a clinic collected data on multiple reasons for non-eligibility, the interpretation of the plot is as follows: \n\u2022 If the primary reason is reported in the \"reason\" column, and other reasons are reported in the \"other\" column, then the denominator of the bar chart is the number of clients not eligible for iCAB/RPV. \n\u2022 If all not eligible reasons are reported, separated by commas, then the denominator of the bar chart is the total number of reasons provided for non-eligibility among clients not eligible for iCAB/RPV.",
  
  # ========== Prescribed Section ==========
  "prescribed_overall",    "Prescribed Overall",                       "This plot shows the percent of people who have been prescribed LAI ART. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded).",
  "sex7",                  "Prescribed by Sex",                        "This plot shows the percent of people who have been prescribed LAI ART, by sex. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nTo compare whether clients who were ever prescribed for LAI ART  differ from clients who were never prescribed LAI ART for the sex variable, users can compare the bars (prescribed LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of sex).",
  "race7",                 "Prescribed by Race",                       "This plot shows the percent of people who have been prescribed LAI ART, by race. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nTo compare whether clients who were ever prescribed LAI ART differ from clients who were never prescribed LAI ART for the race variable, users can compare the bars (ever prescribed LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of race).",
  "ethnicity7",            "Prescribed by Ethnicity",                  "This plot shows the percent of people who have been prescribed LAI ART, by ethnicity. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nTo compare whether clients who were ever prescribed LAI ART differ from clients who were never prescribed LAI ART for the ethnicity variable, users can compare the bars (ever prescribed LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of ethnicity).",
  "age7",                  "Prescribed by Age",                        "This plot shows the percent of people who have been prescribed LAI ART, by age. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nTo compare whether clients who were ever prescribed LAI ART differ from clients who were never prescribed LAI ART for the age variable, users can compare the bars (ever prescribed LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of age).",
  "insurance7",            "Prescribed by HIV Medication Payor",       "This plot shows the percent of people who have been prescribed LAI ART, by HIV medication payor. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who were ever prescribed LAI ART differ from clients who were never prescribed LAI ART for the HIV medicator payor variable, users can compare the bars (ever prescribed LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of HIV medication payor).",
  "keypop7",               "Prescribed by Key Population",             "This plot shows the percent of people who have been prescribed LAI ART, by key population. The denominator is the number of clients interested and eligible (if counseling and screening are consistently recorded) or all people with HIV at the clinic (if counseling and screening are not consistently recorded). \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who were ever prescribed LAI ART differ from clients who were never prescribed LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (ever prescribed LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients ever prescribed LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever prescribed LAI ART regardless of key population).",
  "time7",                 "Prescribed Over Time",                     "Prescribed over time by person shows the number of people prescribed by month. Each person can show up at most 1 time.",
  
  # ========== Accessible Section ==========
  "accessible_overall",    "Accessible Overall",                       "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed.",
  "sex7a",                 "Accessible by Sex",                        "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by sex. \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the sex variable, users can compare the bars (accessible LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of sex).",
  "race7a",                "Accessible by Race",                       "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by race. \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the race variable, users can compare the bars (accessible LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of race).",
  "ethnicity7a",           "Accessible by Ethnicity",                  "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by ethnicity. \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the ethnicity variable, users can compare the bars (accessible LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of ethnicity).",
  "age7a",                 "Accessible by Age",                        "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by age. \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the age variable, users can compare the bars (accessible LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of age).",
  "insurance7a",           "Accessible by HIV Medication Payor",       "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the HIV medicator payor variable, users can compare the bars (accessible LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of HIV medication payor).",
  "keypop7a",              "Accessible by Key Population",             "This plot shows the percent of people with HIV served at your clinic who could financially access LAI ART after being prescribed, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who could financially access LAI ART differ from clients who could not financially access LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (accessible LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients who could financially access LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients who could financially access LAI ART regardless of key population).",
  "time7a",                "Accessible Over Time",                     "Accessible over time shows the number of clients who could financially access LAI ART by prescription month. The height of the bar represents the number of clients prescribed, and the color represents whether LAI ART was financially accessible or not.",
  "not_accessible_reason", "Reasons Not Accessible",                   "Not accessible reasons plot displays the number and percent reporting each reason among those who could not financially access LAI ART when prescribed. \n\nNote that interpretation of this chart will depend on how the variable \"not_accessible_reason\" was coded. A clinic could choose to collect the primary reason for non-accessibility or multiple reasons for non-accessibility. If a clinic collected data on multiple reasons for non-accessibility, the interpretation of the plot is as follows: \n\u2022 If the primary reason is reported in the \"reason\" column, and other reasons are reported in the \"other\" column, then the denominator of the bar chart is the number of clients who could not access iCAB/RPV. \n\u2022 If all not accessible reasons are reported, separated by commas, then the denominator of the bar chart is the total number of reasons provided for non-accessibility among clients who could not access iCAB/RPV.",
  
  # ========== Initiated Section ==========
  "initiated_overall",     "Initiated Overall",                        "This plot shows the percent of people who have initiated LAI ART after being prescribed.",
  "sex8",                  "Initiated by Sex",                         "This plot shows the percent of people who have initiated LAI ART after being prescribed, by sex. \n\nTo compare whether clients who have ever initiated LAI ART  differ from clients who never initiated LAI ART for the sex variable, users can compare the bars (initiated LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients who initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of sex).",
  "race8",                 "Initiated by Race",                        "This plot shows the percent of people who have initiated LAI ART after being prescribed, by race. \n\nTo compare whether clients who have ever initiated LAI ART differ from clients who never initiated LAI ART for the race variable, users can compare the bars (initiated LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients who initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of race).",
  "ethnicity8",            "Initiated by Ethnicity",                   "This plot shows the percent of people who have been initiated LAI ART after being prescribed, by ethnicity. \n\nTo compare whether clients who have ever initiated LAI ART differ from clients who never initiated LAI ART for the ethnicity variable, users can compare the bars (initiated LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients who ever initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of ethnicity).",
  "age8",                  "Initiated by Age",                         "This plot shows the percent of people who have been initiated LAI ART after being prescribed, by age. \n\nTo compare whether clients who have ever initiated LAI ART differ from clients who never initiated LAI ART for the age variable, users can compare the bars (initiated LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients who initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of age).",
  "insurance8",            "Initiated by HIV Medication Payor",        "This plot shows the percent of people who have been initiated LAI ART after being prescribed, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients who have ever initiated LAI ART differ from clients who never initiated LAI ART for the HIV medicator payor variable, users can compare the bars (initiated LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients who initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of HIV medication payor).",
  "keypop8",               "Initiated by Key Population",              "This plot shows the percent of people who have been initiated LAI ART after being prescribed, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients who have ever initiated LAI ART differ from clients who never initiated LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (initiated LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients who initiated LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients ever initiated LAI ART regardless of key population).",
  "time8",                 "Initiated Over Time",                      "Initiated over time shows the number of people initiating by month, based on the date they received their first injection.",
  
  # ========== Sustained Section ==========
  "sustained_overall",     "Sustained Overall",                        "This plot shows the percent of people sustained on LAI ART after being initiated.",
  "sex9",                  "Sustained by Sex",                         "This plot shows the percent of people sustained on LAI ART after being initiated, by sex. \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the sex variable, users can compare the bars (sustained on LAI ART) for each variable category (e.g., female, male). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of sex).",
  "race9",                 "Sustained by Race",                        "This plot shows the percent of people sustained on LAI ART after being initiated, by race. \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the race variable, users can compare the bars (sustained on LAI ART) for each variable category (e.g., Black, White). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of race).",
  "ethnicity9",            "Sustained by Ethnicity",                   "This plot shows the percent of people sustained on LAI ART after being initiated, by ethnicity. \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the ethnicity variable, users can compare the bars (sustained on LAI ART) for each variable category (e.g., Hispanic, Not Hispanic). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of ethnicity).",
  "age9",                  "Sustained by Age",                         "This plot shows the percent of people sustained on LAI ART after being initiated, by age. \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the age variable, users can compare the bars (sustained on LAI ART) for each variable category (e.g., age 18-24, 25-34). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of age).",
  "insurance9",            "Sustained by HIV Medication Payor",        "This plot shows the percent of people sustained on LAI ART after being initiated, by HIV medication payor. \n\nThe HIV medicator payor variable is created by combining two variables: health_care_coverage (the primary source of health care coverage the client had for any part of the reporting period; includes private insurance, Medicare, Medicaid, Veterans Health Administration, Indian Health Service, other health plans, or no insurance/uninsured) and secondary_payor (the payor of HIV medications if different or supplemental from health care coverage; includes ADAP and patient assistance programs). \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the HIV medicator payor variable, users can compare the bars (sustained on LAI ART) for each variable category (e.g., private insurance, uninsured-ADAP). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of HIV medication payor).",
  "keypop9",               "Sustained by Key Population",              "This plot shows the percent of people sustained on LAI ART after being initiated, by key population. \n\nKey populations include patients with different housing or employment status, poverty level, primary language, incarceration history, or other social determinants of health measured by the clinic. \n\nTo compare whether clients sustained on LAI ART differ from clients who discontinued LAI ART for the key population variable, users can first select a key population (e.g., patients with different housing status) and then compare the bars (sustained on LAI ART) for each variable category (e.g., patients with different housing status). Differences in these values represent a care gap where one variable category are over or under represented among clients sustained on LAI ART, relative to their representativeness at the clinic. The dotted line indicates the clinic average (patients sustained on LAI ART regardless of key population).",
  "time9",                 "Time Spent on iCAB/RPV",                   "Time spent on iCAB/RPV shows the number of days that each person has spent on iCAB/RPV in the data, to date. The horizontal axis shows the amount of time spent on iCAB/RPV. The color shows whether they are sustained or have discontinued. The heigh of the bar shows the number of people. This provides a high-level overview of how long clients at your clinic have been on iCAB/RPV.",
  "discontinued_reason",   "Reasons Discontinued",                     "Discontinued reasons plot displays the number and percent reporting each reason among those who discontinued LAI ART. \n\nNote that interpretation of this chart will depend on how the variable \"discontinued_reason\" was coded. A clinic could choose to collect the primary reason for discontinuation or multiple reasons for discontinuation. If a clinic collected data on multiple reasons for discontinuation, the interpretation of the plot is as follows: \n\u2022 If the primary reason is reported in the \"reason\" column, and other reasons are reported in the \"other\" column, then the denominator of the bar chart is the number of clients who discontinued iCAB/RPV. \n\u2022 If all discontinued reasons are reported, separated by commas, then the denominator of the bar chart is the total number of reasons provided for discontinuation among clients who discontinued iCAB/RPV.",
  
  # ========== Clinical Outcomes Section ==========
  "ontime_status",         "On Time Injections",                                 NA,
  "ontime_monthly",        "On Time by Days Since Prior Injection (Monthly)",    "\"On time injections by days since prior injection\" shows how early or late particular injections were, with the on time injection region shaded in gray. There is a plot for monthly injection intervals and a plot for bimonthly injection intervals. If a clinic observes many injections delivered late or injection delivered close to the end of the injection interval, they may want to consider clinic policies, for example scheduling clients at the beginning of the injection interval to provide more time for re-scheduling before the interval ends.",
  "ontime_bimonthly",      "On Time by Days Since Prior Injection (Bimonthly)",  "\"On time injections by days since prior injection\" shows how early or late particular injections were, with the on time injection region shaded in gray. There is a plot for monthly injection intervals and a plot for bimonthly injection intervals. If a clinic observes many injections delivered late or injection delivered close to the end of the injection interval, they may want to consider clinic policies, for example scheduling clients at the beginning of the injection interval to provide more time for re-scheduling before the interval ends. ",
  "late_pt",               "Late Injections by Client",                          "\"Late injections by client\" shows the distribution of late injections, by client. This plot allows clinics to examine whether late injections are concentrated among a few clients or whether many clients are experiencing late injections once or twice.",
  "early_pt",              "Early Injections by Client",                         "\"Early injections by client\" shows the distribution of early injections, by client. This plot allows clinics to examine whether early injections are concentrated among a few clients or whether many clients are experiencing early injections once or twice.",
  
  # ========== Viral Load Section ==========
  "vl_time_to_vs",         "Time to Viral Suppression",                          "This plot shows the percent of clients who achieve viral suppression at key time points, among clients who started iCAB/RPV with viremia. The number in the parentheses at the bottom of each bar indicates how many clients contributed to that data point.  The sooner the plot shows dark orange bars, the shorter the time to viral suppression for clients who initiate with viremia.  Ideally the time to viral suppression will be short and reach near 100%. \n\nThe plot is calculated using the Kaplan-Meier estimator. This gives a conservative, statistical estimate of the time to viral suppression, that accounts for the uncertainty and potential bias due to clients discontinuing before they reach suppression and clients having variable follow-up time. Therefore, the percentages in the plots are statistical estimates, not actual raw percentages and numbers. The number of people contributing data (in parentheses) can give a sense of how certain or uncertain the estimate is.",
  "time_to_el_vl1",        "Time to Elevated VL, initiated suppressed",          "This plot shows the percent of clients who had an elevated viral load at key time points, among clients who started iCAB/RPV virally suppressed. The number in the parentheses at the bottom of each bar indicates how many clients contributed to that data point.  The sooner the plot shows dark blue bars, the shorter the time to elevated viral load for clients who initiate while virally suppressed. Ideally time to first elevated viral load will be long, and the percentage will remain low. \n\nThe plot is calculated using the Kaplan-Meier estimator. This gives a conservative, statistical estimate of the time to first raised viral load, that accounts for the uncertainty and potential bias due to clients discontinuing before they have a raised viral load and clients having variable follow-up time. Therefore, the percentages in the plots are statistical estimates, not actual raw percentages and numbers. The number of people contributing data (in parentheses) can give a sense of how certain or uncertain the estimate is.",
  "time_to_el_vl2",        "Time to Elevated VL, initiated with viremia",        "This plot shows the percent of clients who had an elevated viral load at key time points, among clients who started iCAB/RPV with viremia. The number in the parentheses at the bottom of each bar indicates how many clients contributed to that data point.  The sooner the plot shows dark orange bars, the shorter the time to elevated viral load for clients who initiate with viremia. Ideally time to first elevated viral load will be long, and the percentage will remain low. \n\nThe plot is calculated using the Kaplan-Meier estimator. This gives a conservative, statistical estimate of the time to first raised viral load, that accounts for the uncertainty and potential bias due to clients discontinuing before they have a raised viral load and clients having variable follow-up time. Therefore, the percentages in the plots are statistical estimates, not actual raw percentages and numbers. The number of people contributing data (in parentheses) can give a sense of how certain or uncertain the estimate is.",
  "time_to_failure1",      "Time to Treatment Failure, initiated suppressed",    "This plot shows the percent of clients who had treatment failure at key time points, among clients who started iCAB/RPV virally suppressed. The number in the parentheses at the bottom of each bar indicates how many clients contributed to that data point.  The sooner the plot shows dark blue bars, the shorter the time to treatment failure for clients who initiate while virally suppressed. Ideally time to first treatment failure will be long, and the percentage will remain low. \n\nThe plot is calculated using the Kaplan-Meier estimator. This gives a conservative, statistical estimate of the time to first treatment failure, that accounts for the uncertainty and potential bias due to clients discontinuing before they have treatment failure and clients having variable follow-up time. Therefore, the percentages in the plots are statistical estimates, not actual raw percentages and numbers. The number of people contributing data (in parentheses) can give a sense of how certain or uncertain the estimate is.",
  "time_to_failure2",      "Time to Treatment Failure, initiated with viremia",  "This plot shows the percent of clients who had treatment failure at key time points, among clients who started iCAB/RPV with viremia. The number in the parentheses at the bottom of each bar indicates how many clients contributed to that data point.  The sooner the plot shows dark blue bars, the shorter the time to treatment failure for clients who initiate with viremia. Ideally time to first treatment failure will be long, and the percentage will remain low. \n\nThe plot is calculated using the Kaplan-Meier estimator. This gives a conservative, statistical estimate of the time to first treatment failure, that accounts for the uncertainty and potential bias due to clients discontinuing before they have treatment failure and clients having variable follow-up time. Therefore, the percentages in the plots are statistical estimates, not actual raw percentages and numbers. The number of people contributing data (in parentheses) can give a sense of how certain or uncertain the estimate is.",
  "clinic_level_vl",       "Clinic Level Viral Load",                            "This plot shows the count or percent of people with a viral load above/below a chosen threshold in a chosen time period (every 3 months, every 6 months, or every 12 months), stratified by whether or not they were ever on LAI ART during that time period. Three bar charts are shown: clients on LAI ART (left), clients on oral ART (middle), and all clients on ART (right). \n\nNote that, while each person can only contribute 1 most recent viral load result per time period, that does not mean that each person appears in every period. In fact, the population of people in each period can vary widely depending on who received a viral load test during that period, contributing to changes in percent or count suppressed. Therefore, this metric should be considered preliminary and interpreted with caution."
) |>
  mutate(
    page = case_when(
      str_detect(section_id, "lai_care_gap|assessed_outcomes") ~ "lai_overview",
      str_detect(section_id, "vl") ~ "vl_page",
      str_detect(section_id, "failure") ~ "vl_page",
      str_detect(section_id, "ontime") ~ "inj_page",
      str_detect(section_id, "_pt") ~ "inj_page",
      str_detect(section_id, "1$") ~ "demographics_page",
      str_detect(section_id, "1b$") ~ "demo_by_lai",
      str_detect(section_id, "2$|assessed|2_event") ~ "Assessed",
      str_detect(section_id, "3$|counseled|3_event") ~ "Counseled",
      str_detect(section_id, "4$|interested|4_event") ~ "Interested",
      str_detect(section_id, "5$|screened|5_event") ~ "Screened",
      str_detect(section_id, "6$|eligible|6_event") ~ "Eligible",
      str_detect(section_id, "7$|prescribed") ~ "Prescribed",
      str_detect(section_id, "7a$|accessible") ~ "Accessible",
      str_detect(section_id, "8$|initiated") ~ "Initiated",
      str_detect(section_id, "9$|sustained|discontinued") ~ "Sustained",
    ),
    group_name = case_when(
      str_detect(section_id, "sex") ~ "Sex",
      str_detect(section_id, "race") ~ "Race",
      str_detect(section_id, "ethnicity") ~ "Ethnicity",
      str_detect(section_id, "age") ~ "Age",
      str_detect(section_id, "insurance") ~ "HIV Medication Payor",
      str_detect(section_id, "keypop") ~ "Key Population"
  )
)

# ============================================================================
# Helper Function: create_details_button
# ============================================================================
#' Create a Details Button with Popover
#'
#' @param section_id Character. The section identifier to look up in details_lookup.
#'
#' @return A tagList containing an actionButton and a conditionalPanel with
#'         the matching title and text, or NULL if section_id not found.
#'
#' @details
#' The button is styled as a small secondary action button with a circle-info icon.
#' Clicking the button toggles a simple details panel below it.
#' If the section_id is not found in the lookup table, silently returns NULL.
create_details_button <- function(section_id) {
  lookup <- details_lookup |>
    filter(section_id == !!section_id)
  
  if (nrow(lookup) == 0) {
    return(NULL)
  }
  
  title <- lookup$details_title[1]
  text <- lookup$details_text[1]
  button_id <- paste0(section_id, "_details_btn")
  panel_id <- paste0(section_id, "_details_panel")
  
  # Use a div with relative positioning to contain the absolutely positioned popover
  div(
    style = "position: relative; display: inline-block;",
    tagList(
      actionButton(
        inputId = button_id,
        label = "Details",
        icon = icon("circle-info"),
        class = "details-toggle-btn"
      ),
      conditionalPanel(
        condition = sprintf("input.%s %% 2 == 1", button_id),
        div(
          # Absolute positioning for the popover box, centered
          style = "position: absolute; z-index: 1000; margin-top: 10px; left: 50%; transform: translateX(-50%); width: 40vw;",
          box(
            id = panel_id,
            class = "details-panel",
            title = div(
              class = "details-title-wrap", style = "font-size: 15px;",
              strong(title),
              tags$button(
                type = "button",
                class = "details-close-btn",
                `aria-label` = "Close details",
                HTML("&times;"),
                onclick = sprintf("$('#%s').trigger('click');", button_id)
              )
            ),
            status = "info",
            solidHeader = TRUE,
            width = 12,
            div(
              class = "box-body",
              tags$span(style = "font-size: 14px;", HTML(str_replace_all(text, "\n", "<br>")))
            )
          )
        )
      )
    )
  )
}
